theme = "catppuccin_mocha"

[editor]
bufferline = "always"
color-modes = true
cursorline = true
line-number = "relative"
cursor-shape = { insert = "bar", normal = "block", select = "underline" }
indent-guides = { render = true }