[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }
language-server = { command = "nil" }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = [ "quiet", "-" ] }