[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra", args = [ "-" ] }
language-server = { command = "nil" }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = [ "quiet", "-" ] }